(function(){
'use strict';

const V42_STATE_KEY='mnltDerbyV2';
const V42_MEDIA_DB='mnltDerbyMedia';
const V42_MEDIA_STORE='photos';
const V42_SAFETY_DB='mnltDerbySafetyV42';
const V42_SAFETY_STORE='snapshots';
const V42_FORMAT='MNLT_DERBY_FULL_BACKUP';
const V42_KEEP=20;
let v42SnapshotTimer=null,v42SnapshotBusy=false,v42RestoreArmed=false;

function v42Clone(v){try{return JSON.parse(JSON.stringify(v))}catch(e){return null}}
function v42IsoForFile(){return new Date().toISOString().replace(/[:.]/g,'-')}
function v42FmtTime(v){try{return new Date(v).toLocaleString()}catch(e){return String(v||'')}}
function v42OpenDb(name,version,upgrade){return new Promise((resolve,reject)=>{const q=indexedDB.open(name,version);q.onupgradeneeded=()=>upgrade&&upgrade(q.result);q.onsuccess=()=>resolve(q.result);q.onerror=()=>reject(q.error)})}
function v42OpenMedia(){return v42OpenDb(V42_MEDIA_DB,1,db=>{if(!db.objectStoreNames.contains(V42_MEDIA_STORE))db.createObjectStore(V42_MEDIA_STORE)})}
function v42OpenSafety(){return v42OpenDb(V42_SAFETY_DB,1,db=>{if(!db.objectStoreNames.contains(V42_SAFETY_STORE))db.createObjectStore(V42_SAFETY_STORE,{keyPath:'id'})})}
function v42StoreAll(store){return new Promise((resolve,reject)=>{const out=[];const q=store.openCursor();q.onsuccess=()=>{const c=q.result;if(!c)return resolve(out);out.push({key:c.key,value:c.value});c.continue()};q.onerror=()=>reject(q.error)})}
async function v42ReadPhotoBlobs(){const db=await v42OpenMedia();try{const tx=db.transaction(V42_MEDIA_STORE,'readonly');return await v42StoreAll(tx.objectStore(V42_MEDIA_STORE))}finally{db.close()}}
async function v42ReplacePhotos(items){const db=await v42OpenMedia();try{await new Promise((resolve,reject)=>{const tx=db.transaction(V42_MEDIA_STORE,'readwrite'),s=tx.objectStore(V42_MEDIA_STORE);s.clear();(items||[]).forEach(x=>s.put(x.value,x.key));tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error);tx.onabort=()=>reject(tx.error)})}finally{db.close()}}
function v42BlobToDataUrl(blob){return new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=()=>reject(r.error);r.readAsDataURL(blob)})}
function v42DataUrlToBlob(data){const m=String(data||'').match(/^data:([^;,]+)?(?:;base64)?,(.*)$/s);if(!m)throw Error('Invalid photo data');const mime=m[1]||'application/octet-stream',raw=atob(m[2]),a=new Uint8Array(raw.length);for(let i=0;i<raw.length;i++)a[i]=raw.charCodeAt(i);return new Blob([a],{type:mime})}
async function v42PortablePackage(){const photos=await v42ReadPhotoBlobs(),encoded=[];for(const x of photos)encoded.push({key:x.key,type:x.value?.type||'image/jpeg',size:x.value?.size||0,data:await v42BlobToDataUrl(x.value)});return{format:V42_FORMAT,schema:1,appVersion:'v42',exportedAt:new Date().toISOString(),state:v42Clone(S),photos:encoded}}
function v42DownloadJson(obj,name){const blob=new Blob([JSON.stringify(obj)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(a.href),1200)}
function v42Counts(state){const regs=Array.isArray(state?.registrations)?state.registrations.length:0,trad=Array.isArray(state?.racers)?state.racers.length:0,tradHeats=Array.isArray(state?.heats)?state.heats.length:0,mod=Array.isArray(state?.modified?.raceRacers)?state.modified.raceRacers.length:0,modHeats=Array.isArray(state?.modified?.heats)?state.modified.heats.length:0;return{regs,trad,tradHeats,mod,modHeats}}
function v42ValidState(state){return !!state&&typeof state==='object'&&Array.isArray(state.registrations)&&Array.isArray(state.racers)&&Array.isArray(state.heats)}
async function v42DownloadFull(){try{v42SetStatus('Building full backup…');const p=await v42PortablePackage();v42DownloadJson(p,`MNLT_Derby_FULL_Backup_${v42IsoForFile()}.json`);await v42MakeSafetySnapshot('manual-download');v42SetStatus(`Full backup downloaded • ${p.photos.length} car photo${p.photos.length===1?'':'s'} included`);toast('Full Derby backup downloaded.')}catch(e){console.error(e);v42SetStatus('Backup failed — try again before leaving this computer.');toast('Full backup could not be created.')}}

async function v42MakeSafetySnapshot(reason){if(v42SnapshotBusy)return;v42SnapshotBusy=true;try{const state=v42Clone(S);if(!state)return;const photos=await v42ReadPhotoBlobs(),snap={id:Date.now(),createdAt:new Date().toISOString(),reason:reason||'autosave',state,photos};const db=await v42OpenSafety();try{await new Promise((resolve,reject)=>{const tx=db.transaction(V42_SAFETY_STORE,'readwrite');tx.objectStore(V42_SAFETY_STORE).put(snap);tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error)});const all=await new Promise((resolve,reject)=>{const tx=db.transaction(V42_SAFETY_STORE,'readonly'),q=tx.objectStore(V42_SAFETY_STORE).getAll();q.onsuccess=()=>resolve(q.result||[]);q.onerror=()=>reject(q.error)});all.sort((a,b)=>b.id-a.id);const old=all.slice(V42_KEEP);if(old.length)await new Promise((resolve,reject)=>{const tx=db.transaction(V42_SAFETY_STORE,'readwrite'),s=tx.objectStore(V42_SAFETY_STORE);old.forEach(x=>s.delete(x.id));tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error)})}finally{db.close()}v42SetStatus(`Auto-saved safely • ${v42FmtTime(snap.createdAt)}`);v42RenderSafetyInfo()}catch(e){console.error(e);v42SetStatus('Local safety copy failed — download a full backup.')}finally{v42SnapshotBusy=false}}
function v42ScheduleSnapshot(reason){clearTimeout(v42SnapshotTimer);v42SnapshotTimer=setTimeout(()=>v42MakeSafetySnapshot(reason||'autosave'),700)}
async function v42LatestSafety(){const db=await v42OpenSafety();try{return await new Promise((resolve,reject)=>{const tx=db.transaction(V42_SAFETY_STORE,'readonly'),q=tx.objectStore(V42_SAFETY_STORE).openCursor(null,'prev');q.onsuccess=()=>resolve(q.result?q.result.value:null);q.onerror=()=>reject(q.error)})}finally{db.close()}}
async function v42SafetyCount(){const db=await v42OpenSafety();try{return await new Promise((resolve,reject)=>{const tx=db.transaction(V42_SAFETY_STORE,'readonly'),q=tx.objectStore(V42_SAFETY_STORE).count();q.onsuccess=()=>resolve(q.result||0);q.onerror=()=>reject(q.error)})}finally{db.close()}}
async function v42RestoreSnapshot(snap){if(!snap||!v42ValidState(snap.state)){toast('Safety snapshot is not valid.');return}try{await v42ReplacePhotos(snap.photos||[]);S=v42Clone(snap.state);ensureState();localStorage.setItem(V42_STATE_KEY,JSON.stringify(S));await v42MakeSafetySnapshot('pre-reload-restored');toast('Safety copy restored. Reloading…');setTimeout(()=>location.reload(),600)}catch(e){console.error(e);toast('Safety copy could not be restored.')}}

function v42NormalizeBackup(obj){if(obj?.format===V42_FORMAT&&v42ValidState(obj.state)){const photos=(obj.photos||[]).map(x=>({key:x.key,value:v42DataUrlToBlob(x.data)}));return{kind:'full',state:obj.state,photos,exportedAt:obj.exportedAt||'',version:obj.appVersion||'',photoCount:photos.length}}if(v42ValidState(obj))return{kind:'legacy',state:obj,photos:null,exportedAt:'',version:'legacy',photoCount:0};throw Error('Not an MNLT Derby backup')}
async function v42ImportFile(file){try{const obj=JSON.parse(await file.text()),pkg=v42NormalizeBackup(obj),c=v42Counts(pkg.state);v42ShowImportReview(file.name,pkg,c)}catch(e){console.error(e);v42SetImport('That file is not a valid MNLT Derby backup.','red')}}
function v42ShowImportReview(name,pkg,c){const host=document.getElementById('v42ImportReview');if(!host)return;host._pkg=pkg;host.innerHTML=`<div class="panel" style="margin-top:12px;border:2px solid #d8a63d;background:#0e1c2c"><h3 style="margin-bottom:6px">Backup Ready to Load</h3><div class="rowMeta">${esc(name)}</div><div class="pills"><span class="pill">${c.regs} registrations</span><span class="pill">${c.trad} Traditional racers</span><span class="pill">${c.tradHeats} Traditional heats</span><span class="pill">${c.mod} Modified racers</span><span class="pill">${c.modHeats} Modified heats</span><span class="pill">${pkg.kind==='full'?pkg.photoCount+' photos':'Legacy state-only backup'}</span></div>${pkg.kind==='legacy'?'<p class="gold"><b>Legacy backup:</b> race data can be restored, but old backup files did not contain car photos.</p>':'<p class="green"><b>Full backup:</b> registrations, check-in, inspections, race cards, generated races, saved heat results, runoffs, and car photos will be restored.</p>'}<div class="actions"><button class="btn primary" id="v42ConfirmImport">RESTORE THIS BACKUP</button><button class="btn" id="v42CancelImport">Cancel</button></div></div>`;document.getElementById('v42ConfirmImport').onclick=()=>v42ApplyImport(pkg);document.getElementById('v42CancelImport').onclick=()=>{host.innerHTML='';host._pkg=null}}
async function v42ApplyImport(pkg){try{v42SetImport('Restoring backup…','gold');await v42MakeSafetySnapshot('before-import');if(pkg.photos)await v42ReplacePhotos(pkg.photos);S=v42Clone(pkg.state);ensureState();localStorage.setItem(V42_STATE_KEY,JSON.stringify(S));await v42MakeSafetySnapshot('after-import');v42SetImport('Backup restored. Reloading…','green');toast('Everything restored. Reloading…');setTimeout(()=>location.reload(),700)}catch(e){console.error(e);v42SetImport('Restore failed. Your previous safety copy is still available.','red');toast('Backup restore failed.')}}

function v42SetStatus(text){const x=document.getElementById('v42AutoStatus');if(x)x.textContent=text}
function v42SetImport(text,cls){const x=document.getElementById('v42ImportStatus');if(x){x.className=cls||'muted';x.textContent=text}}
async function v42RenderSafetyInfo(){const x=document.getElementById('v42SafetyInfo');if(!x)return;try{const latest=await v42LatestSafety(),count=await v42SafetyCount();x.innerHTML=latest?`<b class="green">${count} local safety cop${count===1?'y':'ies'}</b><div class="rowMeta">Latest: ${esc(v42FmtTime(latest.createdAt))}</div>`:'<span class="gold">Creating first safety copy…</span>'}catch(e){x.innerHTML='<span class="gold">Safety-copy status unavailable.</span>'}}
async function v42StorageStatus(){const x=document.getElementById('v42StorageStatus');if(!x||!navigator.storage)return;try{let p=await navigator.storage.persisted?.();if(!p&&navigator.storage.persist)p=await navigator.storage.persist();x.innerHTML=p?'<span class="green">Browser storage protection is enabled.</span>':'<span class="gold">Browser storage is automatic, but keep a downloaded backup for protection against browser-data deletion or computer failure.</span>'}catch(e){x.innerHTML='<span class="gold">Keep a downloaded backup for protection against computer failure.</span>'}}
function v42InstallUi(){
 const admin=document.getElementById('admin');if(!admin)return;
 const panel=document.createElement('div');panel.className='panel';panel.id='v42BackupPanel';panel.style.border='2px solid #4e9b67';panel.innerHTML=`<h2 style="margin-bottom:5px">Backup & Recovery</h2><div style="background:#10271d;border:1px solid #4e9b67;border-radius:10px;padding:11px 12px;margin-bottom:12px"><b class="green">AUTO-SAVE IS ON</b><div class="muted" id="v42AutoStatus" style="margin-top:4px">Protecting your Derby progress…</div></div><p style="margin-top:0">Your work automatically resumes on this computer. For another computer, download one <b>Full Derby Backup</b> and load that file there. The full backup includes race data and car photos.</p><div class="actions"><button class="btn primary" id="v42DownloadFull">DOWNLOAD FULL DERBY BACKUP</button><button class="btn good" id="v42LoadFull">LOAD FULL DERBY BACKUP</button><input id="v42FullFile" class="file" type="file" accept="application/json,.json"><button class="btn" id="v42SafetyNow">MAKE SAFETY COPY NOW</button><button class="btn" id="v42RestoreLatest">RESTORE LATEST SAFETY COPY</button></div><div id="v42ImportStatus" class="muted" style="margin-top:9px"></div><div id="v42ImportReview"></div><div class="grid2" style="margin-top:12px"><div class="rowCard"><b>Same computer</b><div class="rowMeta">Every change is saved immediately in the browser plus rolling safety snapshots.</div><div id="v42SafetyInfo" style="margin-top:7px"></div></div><div class="rowCard"><b>Different computer</b><div class="rowMeta">Download the Full Derby Backup, move the file to the other computer, open v42, and Load Full Derby Backup.</div><div id="v42StorageStatus" class="rowMeta" style="margin-top:7px"></div></div></div><div class="rowMeta" style="margin-top:9px">The Gmail bridge password is intentionally not placed in portable backup files. Race-day progress and car photos are included.</div>`;
 const nav=admin.querySelector('.nav');if(nav)nav.insertAdjacentElement('afterend',panel);else admin.prepend(panel);
 document.getElementById('v42DownloadFull').onclick=v42DownloadFull;
 document.getElementById('v42LoadFull').onclick=()=>document.getElementById('v42FullFile').click();
 document.getElementById('v42FullFile').onchange=e=>{const f=e.target.files?.[0];if(f)v42ImportFile(f);e.target.value=''};
 document.getElementById('v42SafetyNow').onclick=async()=>{await v42MakeSafetySnapshot('manual');toast('Safety copy saved.')};
 document.getElementById('v42RestoreLatest').onclick=async e=>{if(!v42RestoreArmed){v42RestoreArmed=true;e.target.textContent='CLICK AGAIN TO RESTORE LATEST';setTimeout(()=>{v42RestoreArmed=false;e.target.textContent='RESTORE LATEST SAFETY COPY'},4000);return}v42RestoreArmed=false;e.target.textContent='RESTORE LATEST SAFETY COPY';const snap=await v42LatestSafety();if(!snap){toast('No safety copy exists yet.');return}await v42RestoreSnapshot(snap)};
 v42RenderSafetyInfo();v42StorageStatus();
 const oldSave=document.getElementById('saveDerby'),oldLoad=document.getElementById('loadDerby'),oldFile=document.getElementById('loadDerbyFile');if(oldSave){oldSave.textContent='Download Full Backup';oldSave.onclick=v42DownloadFull}if(oldLoad&&oldFile){oldLoad.textContent='Load Full Backup';oldLoad.onclick=()=>oldFile.click();oldFile.onchange=e=>{const f=e.target.files?.[0];if(f)v42ImportFile(f);e.target.value=''}}
}

const v42BasePersist=persist;
persist=function(){v42BasePersist();v42ScheduleSnapshot('autosave')};
window.addEventListener('pageshow',()=>v42ScheduleSnapshot('startup'));
setTimeout(()=>v42MakeSafetySnapshot('startup'),1200);
setTimeout(v42InstallUi,0);
window.MNLTBackupV42={download:v42DownloadFull,snapshot:()=>v42MakeSafetySnapshot('manual-api'),latest:v42LatestSafety};
})();